### PR TITLE
DexNS symbol registration for automated token support at CEW.

### PR DESCRIPTION
**Pull request by Dexaran**
https://github.com/ethereumproject/TokenMint/issues/98

### CODE REVIEW

**Comment by elaineo** [comment]
Can you add a reference to the function definitions for `DexNS_Abstract_Interface`? It would be useful for documentation purposes, if users want to fork or audit the code.

**Comment by Dexaran** [comment]
I have included DexNS interface in this commit: https://github.com/ethereumproject/TokenMint/pull/99/commits/2cbfe577b66f59a34ffbf61ff1afc292d32e44b6

**Comment by Dexaran** [comment]
If you are wondering for the reference implementation, then the main DexNS repo is here: https://github.com/EthereumCommonwealth/DexNS

**Comment by elaineo** [comment]
@Dexaran in which file are the functions defined?

**Comment by Dexaran** [comment]
Here is abstract DexNS interface: https://github.com/EthereumCommonwealth/TokenMint/blob/master/contracts/DexNS_Interface.sol

I can comment functions a bit later.

**Comment by elaineo** [comment]
@Dexaran We need the actual function definitions. I can't merge code that allows users to call functions without knowing what the functions actually do.

**Comment by Dexaran** [comment]
I have referenced DexNS repo for this purpose. Actual functions are currently implemented in DexNS frontend contract: https://github.com/EthereumCommonwealth/DexNS/blob/master/DexNS_Frontend.sol

Frontend contract is calling the storage contract when registering a Name: https://github.com/EthereumCommonwealth/DexNS/blob/master/DexNS_Storage.sol

**Comment by elaineo** [comment]
@Dexaran okay great. If you could add those two links in the code comments, that would be very helpful. Let me know when the updated IcoMachine.sol is deployed (or I can do it, if you want), and I will create a new PR to update the user interface.

**Comment by realcodywburns** [comment]
How is it march already!

**Comment by elaineo** [comment]
@realcodywburns well we were waiting on @Dexaran to add links to the source code of the contracts. Right now, this PR references an interface, but a user who inspects the code does not know what contract will actually execute. Also, if I understand correctly, this contract has not yet been deployed.

**Pull request merged**
