### PR TITLE
Wallet Manager

### PR DESCRIPTION
**Pull request by elaineo**
Issues in #75

### CODE REVIEW

**Comment by kimisan** [comment]
Still can not see the Balances

**Comment by elaineo** [comment]
@kimisan ah, i forgot to deploy. try again :) http://tokenmint.io/#/addr/0xe9a7e26bf5c05fe3bae272d4c940bd7158611ce9

**Comment by kimisan** [comment]
@elaineo 
Still not see the Token Balances.
Only "Token" text showed but no Balances number.

**Comment by elaineo** [comment]
The only tokens in the system right now are BEC, DEX, and ALMS. Do you have token balances for those three?

**Comment by elaineo** [comment]
@kimisan You can see the contract address for tokens created at the very bottom, right? I can add token balance for user-created tokens, sure :)

**Comment by kimisan** [comment]
@elaineo Yap, i can see the total supply and address of the created token. 
But if it can check the token balance will be good.

**Pull request merged**
